version: '3.1'
services:
  builder:
    image: rust:buster
    container_name: rust-builder
    volumes:
      - ./../app:/opt/app
      - ./../lib/1.0.0/linux/amd64:/opt/lib
    ports:
      - 8000:8000    
    working_dir: /opt/app
    tty: true